name: Get Kernel list and save matrix

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo content
        uses: actions/checkout@v2
      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: install python packages
        run: |
          python -m pip install --upgrade pip
          pip install -r scripts/requirements.txt      
      - name: Update matrix file
        run: python scripts/re_matrix.py
      - name: Commit kernel list updates 
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"          
          if git diff --quiet; then
            echo "No changes detected. Skipping commit and push."
          else
            git add data 
            git commit -m "Updating the kernel version list"
            git push
          fi          
      
