name: Get Kernel List

on: [push]

jobs:
    steps:
      - uses: actions/checkout@v5
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: python -m pip install --upgrade pip
      - name: Display kernel list
        run: python scripts/kernel-list.py
